from enum import Enum


class RelationType(str, Enum):
    DIRECT_FORESHADOWING = "DIRECT_FORESHADOWING"
    REINTERPRETATION = "REINTERPRETATION"
    CHARACTER_MOTIVATION = "CHARACTER_MOTIVATION"
    CONTRADICTION = "CONTRADICTION"
    COINCIDENCE = "COINCIDENCE"
    IRRELEVANT = "IRRELEVANT"

    @property
    def is_user_presentable(self) -> bool:
        """COINCIDENCE and IRRELEVANT must never be shown on final user cards."""
        return self not in (RelationType.COINCIDENCE, RelationType.IRRELEVANT)


class FactType(str, Enum):
    EXPLICIT = "EXPLICIT"
    OBSERVATION = "OBSERVATION"
    UNCERTAIN_OBSERVATION = "UNCERTAIN_OBSERVATION"


class KnowledgeStatus(str, Enum):
    BELIEVED = "BELIEVED"
    SUSPECTED = "SUSPECTED"
    UNKNOWN = "UNKNOWN"
    REVEALED_FACT = "REVEALED_FACT"
    CONTRADICTED = "CONTRADICTED"


class ReframeRunStatus(str, Enum):
    QUEUED = "QUEUED"
    REVEAL_PARSED = "REVEAL_PARSED"
    MCP_QUERYING = "MCP_QUERYING"
    CANDIDATES_FOUND = "CANDIDATES_FOUND"
    VERIFYING = "VERIFYING"
    COMPLETED = "COMPLETED"
    ABSTAINED = "ABSTAINED"
    FAILED = "FAILED"


class ExecutionMode(str, Enum):
    OFFLINE_FIXTURE = "OFFLINE_FIXTURE"
    LIVE_GOOGLE = "LIVE_GOOGLE"
    FAIL_CLOSED = "FAIL_CLOSED"



class AbstainReason(str, Enum):
    EVIDENCE_INSUFFICIENT = "EVIDENCE_INSUFFICIENT"
    NO_CANDIDATES = "NO_CANDIDATES"
    MCP_UNAVAILABLE = "MCP_UNAVAILABLE"
    MCP_TIMEOUT = "MCP_TIMEOUT"
    REVEAL_NOT_FOUND = "REVEAL_NOT_FOUND"
    SPOILER_GUARD_BLOCKED = "SPOILER_GUARD_BLOCKED"
    GEMINI_SCHEMA_ERROR = "GEMINI_SCHEMA_ERROR"
    EVIDENCE_CONFLICT = "EVIDENCE_CONFLICT"
